### ISSUE TITLE
Expectations to receive multiple calls to the same method

### ISSUE THREAD

**Issue by joeldrapper** [ioquatix/sus#10]
I’m trying to write an expectation that an object receives multiple calls with different arguments. It looks like this isn’t supported yet.

```ruby
describe Phlex::Compiler do
  let(:compiler) { Phlex::Compiler.new(Example) }

  it "doesn't fold overwritten HTML tag methods" do
    expect(compiler).to receive(:redefine).with_arguments <<~RUBY.chomp
      def template
        title
        @_target << "<article></article>"
      end
    RUBY

    expect(compiler).to receive(:redefine).with_arguments <<~RUBY.chomp
      def title
        @_target << "<h1></h1>"
      end
    RUBY

    compiler.call
  end
end
```

**Comment by ioquatix** [comment]
I always felt like RSpec mock was to much magic. The implicit ordering, which then leads to things like `allow` vs `expect`, and `#once`, `#twice` etc.

I was trying to avoid introducing a lot of complexity, but I understand the use case and have used it myself occasionally.

The amount of statefulness in the test harness required to track tests like this is quite heavy - essentially a list of "match this, then this, then this, etc." and I was never that comfortable for paying such a high price in the complex implementation for a feature that is used very rarely.

What I did feel was okay was, to do something like this instead:

```ruby
describe Phlex::Compiler do
  let(:compiler) { Phlex::Compiler.new(Example) }

  it "doesn't fold overwritten HTML tag methods" do
    templates = []
    mock(compiler) do |mock|
      mock.before(:redefine) do |template|
        templates << template
      end
    end

    compiler.call

    expect(templates).to be == [...]
  end
end
```

**Comment by ioquatix** [comment]
There is now a way to do this:

https://github.com/socketry/sus/blob/05168ff082af8fb95f1a4f74c6bbaf35e3eaffa5/lib/sus/receive.rb#L48-L56

You can make any predicate against `@times` that you want.
