### ISSUE TITLE
Support for Ruby 2.7

### ISSUE THREAD

**Issue by bschrag620** [ioquatix/sus#16]
The current code base doesn't seem to support Ruby 2.7 despite it being part of the test suite matrix. In some testing locally (Ubuntu 20.04) I am unable to run the test suite command locally (`bundle exec bake test`). The issue comes from a syntax error in `it.rb`:

```
sus/lib/sus/it.rb:50: syntax error, unexpected ')' (SyntaxError)
    add It.build(self, ...)
```

According to the article [here ](https://blog.saeloun.com/2019/12/04/ruby-2-7-adds-new-operator-for-arguments-forwarding.html) regarding the addition for argument forwarding, as of 2.7 positional arguments are not supported. I ran into this when I was attempting to add Phlex to a project and was running into a similar error. In an effort to allow Phlex to be 2.7 compatible I ran into `sus` not being 2.7 compatible.

It seems odd that Github actions isn't failing the test suite which leads me to think its a local issue. I have a fix for `it.rb` locally that is passing tests that I'm happy to submit a PR for. However, the `tests:external` seem to be failing due to a similar issue in the `console` gem.

**Comment by bschrag620** [comment]
TIL Ruby 2.7.3 supports positional arguments but 2.7.2 does not. Happy to submit the PR to give support back to 2.7.2 but understand if this isn't wanted.

**Comment by ioquatix** [comment]
Ruby 2.7.x where x < 6 has security issues. So, I'm hesitant to invest a lot of energy into maintaining support for older releases 2.7 - especially that it will be EOL soon.

I don't have a really strong opinion about it, but I am happy with the current level of support. If it's causing you a significant pain, I'm willing to consider it, but can you tell me more details about your pain point and the scope of your fix?

**Comment by bschrag620** [comment]
I don't think it is a big enough issue to warrant fixing here. Bumping up a few minor versions to remedy the issue seems simple enough. I was initially thinking I needed to move to Ruby 3 - which still may not even be a big deal. For what it's worth to fix the issue requires patching `Sus::Context` module in `it.rb`:
was:
```
	module Context
		def it(...)
			add It.build(self, ...)
		end
	end
```

To give support to 2.7.2 (and likely even 2.6):
```
	module Context
		def it(*args, **kwargs, &blk)
			add It.build(self, *args, **kwargs, &blk)
		end
	end
```

**Comment by ioquatix** [comment]
Ah yep that's totally reasonable patch. However, to your point, I think it's better to move to v2.7.6 - thanks for your thoughts and considerations..
