### ISSUE TITLE
Global hooks?

### ISSUE THREAD

**Issue by joelmoss** [ioquatix/sus#21]
I can see the before, after and around hooks, but these seem to have to be defined in each file. Is there any way to define global hooks that apply to all tests?

**Comment by ioquatix** [comment]
There are no global hooks.

You can make a module and include it.

Alternatively the config provides hooks for the runner, but this isn't the same as global before and after hooks at the test level:

https://github.com/ioquatix/sus/blob/07e61b64270ad5204d30cd093c3eefc92997cfa7/lib/sus/config.rb#L102-L111

Can you let me know what problem you are trying to solve?

**Comment by joelmoss** [comment]
I need to clean the DB before each test to give me a fresh blank slate. Right now I'm defining a `before` hook in each test file, but that is a little cumbersome, and prone to my forgetfulness 😏

**Comment by ioquatix** [comment]
Make a module

```ruby
# fixtures/database_access.rb
module DatabaseAccess
  # Lazy connection if required
  def database_connection
    unless @database_connection
      @database_connection = Database.connect
      @database_connection.begin_transaction
    end
    return @database_connection
  end

  def after
    @database_connection.abort_transaction
  end
end
```

Use it like this:

```ruby
# test/database.rb
require 'database_connection'

describe MyModel do
  include DatabaseConnection
  it "can get a connection" do
    expect(database_connection).not.to be_nil
  end
end
```

**Comment by joelmoss** [comment]
Yeah, that's better, but it still requires me to include it in each and every test file, resulting in the same problem.

**Comment by ioquatix** [comment]
There is always a trade off between implicit and explicit like in this case, but for tests, I think too much implicit state makes it hard to reason about what's going on. I think it's best you can look at one test file and understand what is going on - specifically this is important for being able to load tests files in parallel and without depending on a global configuration, i.e. all test files are self contained.

**Comment by joelmoss** [comment]
Fair enough. Thanks
